[package]
name = "tracing-jump-start"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "=0.1.40"
tracing-subscriber = { version = "=0.3.18", features = ["valuable-serde", "json", "env-filter"] }
tracing-appender = "=0.2.3"
anyhow = "=1.0.86"